Repository Arsen-Lovecraft/GJ82, pull requests merged in 2025-06, with the labels that each got.

#3 A button and A door simple back-end without visuals
  Godot_project/_not_for_export/test_door_and_button_interactive/main_test_level_door_and_button_1.gd
  Godot_project/_not_for_export/test_door_and_button_interactive/main_test_level_door_and_button_1.gd.uid
  Godot_project/_not_for_export/test_door_and_button_interactive/main_test_level_door_and_button_1.tscn
  Godot_project/_not_for_export/test_door_and_button_interactive/test_button_label.gd
  Godot_project/_not_for_export/test_door_and_button_interactive/test_button_label.gd.uid
  Godot_project/_not_for_export/test_door_and_button_interactive/test_character.gd
  Godot_project/_not_for_export/test_door_and_button_interactive/test_character.gd.uid
  Godot_project/_not_for_export/test_door_and_button_interactive/test_door_label.gd
  Godot_project/_not_for_export/test_door_and_button_interactive/test_door_label.gd.uid
  Godot_project/_not_for_export/test_door_and_button_interactive/test_level_door_and_button_2.tscn
  Godot_project/globals/scripts/scene_manager.gd
  Godot_project/project.godot
  Godot_project/scenes/interactive_objects/interactive_button.gd
  Godot_project/scenes/interactive_objects/interactive_button.gd.uid
  Godot_project/scenes/interactive_objects/interactive_button.tscn
  Godot_project/scenes/interactive_objects/interactive_door.gd
  Godot_project/scenes/interactive_objects/interactive_door.gd.uid
  Godot_project/scenes/interactive_objects/interactive_door.tscn
  Godot_project/scenes/utility/loading_screen.tscn
Labels: enhancement

#6 On collide shaders
  Godot_project/scenes/levels/level.tscn
  Godot_project/scenes/player/player.gd
  Godot_project/scenes/player/player.tscn
  Godot_project/scenes/player/sonar.gd
  Godot_project/scenes/player/sonar.tscn
  Godot_project/scenes/player/step.gd
  Godot_project/scenes/player/step.gd.uid
  Godot_project/scenes/player/step.tscn
  Godot_project/scenes/static_environment/static_environment.tscn
Labels: enhancement

#17 Platform is disappearning as soon as sonar is gone
  Godot_project/scenes/interactive_objects/emerging_platform.gd
  Godot_project/scenes/interactive_objects/emerging_platform.tscn
  Godot_project/scenes/player/player.tscn
Labels: bug

#19 Fixes (see description)
  Godot_project/addons/easy_audio/audio.gd
  Godot_project/assets/localizations/translation_template.csv
  Godot_project/assets/localizations/translation_template.csv.import
  Godot_project/assets/localizations/translations.csv
  Godot_project/assets/localizations/translations.csv.import
  Godot_project/assets/sounds/air_trail.wav
  Godot_project/assets/sounds/air_trail.wav.import
  Godot_project/assets/sounds/ait_trail.wav
  Godot_project/assets/sounds/ait_trail.wav.import
  Godot_project/custom_resources/utility/rsettings_config.gd
  Godot_project/project.godot
  Godot_project/scenes/levels/level_1_introduction.tscn
  Godot_project/scenes/levels/level_2_jump.tscn
  Godot_project/scenes/levels/level_3_button.tscn
  Godot_project/scenes/levels/level_4_emerging_platoform.tscn
  Godot_project/scenes/player/player.tscn
  Godot_project/scenes/settings/setting_windows/controls_settings_ui.gd
  translations.xlsx
Labels: enhancement

#22 Credits and russian font
  Godot_project/assets/fonts/ru.ttf
  Godot_project/assets/fonts/ru.ttf.import
  Godot_project/assets/localizations/translations.csv
  Godot_project/assets/localizations/translations.csv.import
  Godot_project/custom_resources/utility/rsettings_config.gd
  Godot_project/export_presets.cfg
  Godot_project/globals/Theme/Global.tres
  Godot_project/project.godot
  Godot_project/scenes/levels/level_2_jumpL2.tscn
  Godot_project/scenes/levels/level_3_buttonL3.tscn
  Godot_project/scenes/levels/level_4_emergingPlatformL4.tscn
  Godot_project/scenes/levels/level_5_EmergeTripletsL5.tscn
  Godot_project/scenes/levels/level_6_movingTroubleL6.tscn
  Godot_project/scenes/settings/setting_windows/game_settings_ui.tscn
  Godot_project/scenes/settings/settings_ui.tscn
  Godot_project/scenes/utility/loading_screen.tscn
  translations.xlsx
Labels: playtest

#23 Step corrections and slight modifications
  Godot_project/scenes/player/player.tscn
  Godot_project/scenes/player/step.tscn
  Godot_project/scenes/ui/win_scene.tscn
Labels: bug, enhancement
